language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get install ocaml zlib1g-dev libgc-dev gcc-multilib g++-multilib -y
  - git clone https://github.com/HaxeFoundation/neko.git ~/neko && cd ~/neko && make && sudo make install && cd $TRAVIS_BUILD_DIR
  - git clone --recursive https://github.com/HaxeFoundation/haxe.git ~/haxe && cd ~/haxe && make && make tools && sudo make install && cd $TRAVIS_BUILD_DIR
  - mkdir ~/haxelib && haxelib setup ~/haxelib
  - haxelib dev hxcpp $TRAVIS_BUILD_DIR

script:
  - cd build-tool/haxe
  - haxe run.hxml
  - cd ../../runtime
  - haxelib run hxcpp BuildLibs.xml
  - haxelib run hxcpp BuildLibs.xml -DHXCPP_M64
  - cd ../test/ndlls
  - haxe compile.hxml && ./cpp/Test
  - haxe compile64.hxml && ./cpp64/Test
  - cd ~/haxe/tests/unit
  - haxe compile-cpp.hxml && ./cpp/Test-debug && rm -rf cpp
  - haxe compile-cpp.hxml -D HXCPP_M64 && ./cpp/Test-debug
