language: cpp

sudo: required

env:
  global:
    - HXCPP_COMPILE_CACHE=~/hxcache

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - ARCH=32
      install:
        - bash tools/haxe/build_linux.sh
        - travis_retry sudo apt-get install gcc-multilib g++-multilib -y;
    - os: linux
      dist: trusty
      env:
        - ARCH=64
      install:
        - bash tools/haxe/build_linux.sh
    - os: osx
      osx_image: xcode9.1
      env:
        - ARCH=32
      install:
        - bash tools/haxe/build_osx.sh;
    - os: osx
      osx_image: xcode9.1
      env:
        - ARCH=64
      install:
        - bash tools/haxe/build_osx.sh;

script:
  - cd ${TRAVIS_BUILD_DIR}/tools/run
  - haxe compile.hxml
  - cd ${TRAVIS_BUILD_DIR}/tools/hxcpp
  - haxe compile.hxml
  - cd ${TRAVIS_BUILD_DIR}/project
  - haxe compile-cppia.hxml
  - cd ${TRAVIS_BUILD_DIR}/test
  - haxe --run RunTests cffi
  - haxe --run RunTests haxe
  - haxe --run RunTests telemetry
  - haxe --run RunTests std${ARCH}
  - haxe --run RunTests debugger
  - haxe --run RunTests native
  - cd ~/haxe/tests/unit
  - haxe compile-cpp.hxml -D HXCPP_M${ARCH} && ./bin/cpp/TestMain-debug
  - haxe compile-cppia.hxml -debug && haxelib run hxcpp ./bin/unit.cppia
